(()=>{
const HIST_RATE=.303,SAFE_RATE=.07;
const money=n=>'₪'+Math.round(+n||0).toLocaleString('he-IL');
function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn()}
function style(){if(document.getElementById('mfPremiumStyle'))return;const s=document.createElement('style');s.id='mfPremiumStyle';s.textContent=`
@keyframes mfFade{from{opacity:0}to{opacity:1}}@keyframes mfLift{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@keyframes mfPop{0%{opacity:0;transform:scale(.72)}55%{opacity:1;transform:scale(1.08)}100%{transform:scale(1)}}@keyframes mfPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.07)}}@keyframes mfShine{from{transform:translateX(-140%) skewX(-18deg)}to{transform:translateX(320%) skewX(-18deg)}}@keyframes mfConfetti{0%{transform:translateY(8vh) rotate(0);opacity:0}10%{opacity:1}100%{transform:translateY(-115vh) rotate(720deg);opacity:0}}@keyframes mfGlow{0%,100%{box-shadow:0 0 0 #43d7c800}50%{box-shadow:0 0 24px #43d7c844}}
.mfPremiumIn{animation:mfLift .28s ease both}.mfTap{transition:transform .14s ease,filter .14s ease}.mfTap:active{transform:scale(.975);filter:brightness(1.08)}
.mfStreakBtn{position:relative;overflow:hidden;font-size:12px!important;line-height:1.05}.mfStreakBtn.hot{animation:mfPulse 1.9s ease-in-out infinite}.mfStreakBtn:after,.mfShimmer:after{content:"";position:absolute;inset:-25% auto -25% -40%;width:28%;background:linear-gradient(90deg,transparent,#ffffff4a,transparent);animation:mfShine 1.35s ease;pointer-events:none}
.mfAch{position:fixed;inset:0;z-index:25000;display:grid;place-items:center;background:#050b14dd;backdrop-filter:blur(14px);animation:mfFade .16s ease}.mfAchCard{width:min(88vw,390px);text-align:center;background:linear-gradient(145deg,#123441,#0b1c2d);border:1px solid #2a5369;border-radius:28px;padding:28px 22px;box-shadow:0 22px 90px #0009;animation:mfPop .42s cubic-bezier(.2,.8,.2,1)}.mfAchIcon{font-size:54px}.mfAchTitle{font-size:25px;font-weight:950;margin-top:8px}.mfAchSub{color:#9fb0c4;margin-top:6px;line-height:1.5}.mfConfetti{position:fixed;bottom:-20px;width:9px;height:17px;border-radius:3px;z-index:25001;animation:mfConfetti 1.45s ease-out forwards;pointer-events:none}
.mfInsightCard,.mfForecast{position:relative;overflow:hidden}.mfInsightCard{border-right:3px solid #43d7c8}.mfForecast{animation:mfGlow 3s ease-in-out 1}.mfForecast .mfMetric{background:#111f32;border:1px solid #24344a;border-radius:15px;padding:11px}.mfForecastGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.mfForecastGrid b{display:block;margin-top:4px;font-size:19px}.mfNote{font-size:11px;color:#9fb0c4;line-height:1.45;margin-top:10px}
.prog i{transform-origin:right center;transition:width .65s cubic-bezier(.2,.8,.2,1)}.c,.mini,.txn,.rank,.datebox{transition:transform .16s ease,border-color .2s ease,box-shadow .2s ease}.c:active,.mini:active{transform:scale(.992)}
@media(max-width:390px){.mfForecastGrid{grid-template-columns:1fr}.mfAchCard{width:90vw}}
`;document.head.appendChild(s)}
function netPeriod(a,p){return(a||[]).filter(x=>x.person===p).reduce((sum,x)=>sum+(x.kind==='income'?+x.amount:-x.amount),0)}
function itayStreak(){if(typeof ws!=='function')return 0;const goal=+(window.set?.itay_weekly_goal||1779.41);let n=0;for(let k=0;k<52;k++){const w=ws(-k),v=netPeriod(w.a,'איתי');if(v>=goal)n++;else break}return n}
function noaStreak(){if(typeof ms!=='function')return 0;const goal=+(window.set?.noa_monthly_goal||7000);let n=0;for(let k=0;k<24;k++){const m=ms(-k),v=netPeriod(m.a,'נועה');if(v>=goal)n++;else break}return n}
function streakOverlay(){const i=itayStreak(),n=noaStreak();const b=document.createElement('div');b.className='mfAch';b.innerHTML=`<div class="mfAchCard"><div class="mfAchIcon">🔥</div><div class="mfAchTitle">הסטריק שלכם</div><div class="mfForecastGrid" style="margin-top:16px"><div class="mfMetric"><span class="mut sm">איתי</span><b>${i} שבועות</b></div><div class="mfMetric"><span class="mut sm">נועה</span><b>${n} חודשים</b></div></div><button id="mfLogoutInside" class="btn s" style="width:100%;margin-top:14px">יציאה מהחשבון</button><button id="mfCloseStreak" class="btn p" style="width:100%;margin-top:8px">סגור</button></div>`;document.body.appendChild(b);b.querySelector('#mfCloseStreak').onclick=()=>b.remove();b.querySelector('#mfLogoutInside').onclick=()=>typeof logout==='function'&&logout();b.onclick=e=>{if(e.target===b)b.remove()}}
function replaceLogout(){const h=document.querySelector('header .ha');if(!h||document.getElementById('mfStreak'))return;const old=[...h.querySelectorAll('button')].find(x=>(x.getAttribute('onclick')||'').includes('logout'));if(!old)return;const i=itayStreak(),n=noaStreak(),best=Math.max(i,n);const b=document.createElement('button');b.id='mfStreak';b.className='ib mfStreakBtn mfTap'+(best>0?' hot':'');b.innerHTML=`🔥<span style="display:block;font-size:9px;margin-top:1px">${best}</span>`;b.title='סטריק';b.onclick=streakOverlay;old.replaceWith(b)}
function autoInsightText(){if(typeof ws!=='function'||typeof ms!=='function')return'';const w=ws(0),pw=ws(-1),m=ms(0),pm=ms(-1);const d=w.s-pw.s;const parts=[];if(w.s>0)parts.push(`השבוע אתם בחיסכון חיובי של <b>${money(w.s)}</b>`);else if(w.s<0)parts.push(`השבוע אתם במינוס של <b>${money(Math.abs(w.s))}</b>`);if(pw.a?.length)parts.push(d>=0?`שיפור של <b>${money(d)}</b> לעומת השבוע הקודם`:`ירידה של <b>${money(Math.abs(d))}</b> לעומת השבוע הקודם`);if(pm.i||pm.e){const md=m.s-pm.s;parts.push(md>=0?`החודש חזק יותר בכ־<b>${money(md)}</b>`:`החודש חלש יותר בכ־<b>${money(Math.abs(md))}</b>`)}return parts.join('. ')+'.'}
function addAutoInsight(){const sec=document.getElementById('insights');if(!sec||sec.querySelector('#mfAutoInsight'))return;const anchor=sec.querySelector('.c.hero')||sec.firstElementChild;const c=document.createElement('div');c.id='mfAutoInsight';c.className='c mfInsightCard mfPremiumIn';c.innerHTML=`<div class="sectiontitle"><h2>✨ תובנה אוטומטית</h2><span class="badge">חי</span></div><div id="mfInsightText" class="ins">${autoInsightText()||'עוד אין מספיק נתונים כדי לבנות תובנה.'}</div>`;anchor?.after(c)}
function investmentValues(){const p=+(localStorage.getItem('mf_inv_price_agorot')||0),units=21349.467;return{p,v:units*p/100}}
function addForecast(){const sec=document.getElementById('goals');if(!sec||sec.querySelector('#mfInvestmentForecast'))return;const x=investmentValues();if(!x.p)return;const release=new Date((window.set?.itay_release_date||'2027-04-04')+'T00:00:00'),now=new Date(),years=Math.max(0,(release-now)/(365.2425*86400000));const hist=x.v*Math.pow(1+HIST_RATE,years),safe=x.v*Math.pow(1+SAFE_RATE,years),gainHist=hist-x.v,gainSafe=safe-x.v;const c=document.createElement('div');c.id='mfInvestmentForecast';c.className='c mfForecast mfPremiumIn';c.innerHTML=`<div class="sectiontitle"><h2>📈 תחזית השקעה עד השחרור</h2><span class="badge">04.04.2027</span></div><div class="mfForecastGrid"><div class="mfMetric"><span class="mut sm">שווי נוכחי</span><b>${money(x.v)}</b></div><div class="mfMetric"><span class="mut sm">לפי 12 החודשים האחרונים · 30.3%</span><b>${money(hist)}</b><div class="good sm">+${money(gainHist)}</div></div><div class="mfMetric"><span class="mut sm">תרחיש שמרני · 7%</span><b>${money(safe)}</b><div class="good sm">+${money(gainSafe)}</div></div><div class="mfMetric"><span class="mut sm">שער נוכחי</span><b>${x.p.toFixed(2)} אג׳</b></div></div><div class="mfNote">התחזית היא סימולציה בלבד ואינה הבטחת תשואה. תשואת 12 החודשים האחרונים יכולה להיות חריגה ולא לחזור על עצמה.</div>`;const dates=[...sec.querySelectorAll('.c')].find(c=>(c.querySelector('h2')?.textContent||'').trim()==='תאריכי יעד');(dates||sec.lastElementChild)?.before(c)}
function achievement(icon,title,sub,key){if(key&&localStorage.getItem('mf_ach_'+key))return;if(key)localStorage.setItem('mf_ach_'+key,'1');const b=document.createElement('div');b.className='mfAch';b.innerHTML=`<div class="mfAchCard"><div class="mfAchIcon">${icon}</div><div class="mfAchTitle">${title}</div><div class="mfAchSub">${sub}</div></div>`;document.body.appendChild(b);for(let i=0;i<26;i++){const c=document.createElement('i');c.className='mfConfetti';c.style.left=(Math.random()*100)+'vw';c.style.background=['#43d7c8','#60a5fa','#f6c765','#fb7185','#4ade80'][i%5];c.style.animationDelay=(Math.random()*.35)+'s';c.style.animationDuration=(1.05+Math.random()*.65)+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),2100)}setTimeout(()=>b.remove(),1650);b.onclick=()=>b.remove()}
function checkAchievements(){if(typeof ws!=='function'||typeof ms!=='function'||typeof calc!=='function')return;const w=ws(0),m=ms(0),it=netPeriod(w.a,'איתי'),no=netPeriod(m.a,'נועה'),ig=+(window.set?.itay_weekly_goal||1779.41),ng=+(window.set?.noa_monthly_goal||7000),weekKey=w.d?.toISOString?.().slice(0,10)||'week',monthKey=new Date().toISOString().slice(0,7);if(it>=ig)achievement('🎯','היעד השבועי הושג!','איתי סגר את היעד השבועי. ממשיכים את הסטריק 🔥','it_'+weekKey);if(no>=ng)achievement('🏆','היעד החודשי הושג!','נועה הגיעה ליעד החודשי. יפה מאוד!','no_'+monthKey);const c=calc(),pct=c.j/Math.max(1,c.g)*100;[25,50,75,100].forEach(mil=>{if(pct>=mil)achievement(mil===100?'👑':'💎',`${mil}% מהיעד המשותף!`,`${money(c.j)} מתוך ${money(c.g)}`,'capital_'+mil)})}
function premiumTouches(){document.querySelectorAll('button,.q,.cat,.datebox,.txn,.mini').forEach(x=>x.classList.add('mfTap'));document.querySelectorAll('.prog i').forEach(x=>{x.style.transition='width .7s cubic-bezier(.2,.8,.2,1)'})}
async function refreshForecast(){const card=document.getElementById('mfInvestmentForecast');if(card)card.remove();addForecast()}
function wrapInvestment(){if(window.__mfInvWrapped)return;window.__mfInvWrapped=1;const old=window.renderInvestment;if(typeof old==='function')window.renderInvestment=function(){const r=old.apply(this,arguments);const card=document.getElementById('investCard');if(card){card.classList.remove('mfShimmer');void card.offsetWidth;card.classList.add('mfShimmer');setTimeout(()=>card.classList.remove('mfShimmer'),1400)}refreshForecast();return r}}
function init(){style();replaceLogout();addAutoInsight();addForecast();premiumTouches();wrapInvestment();setTimeout(checkAchievements,900);const mo=new MutationObserver(()=>{replaceLogout();addAutoInsight();addForecast();premiumTouches()});mo.observe(document.body,{childList:true,subtree:true})}
ready(init)
})();