(()=>{
const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn();
function addStyle(){if(document.getElementById('mfSafe20'))return;const s=document.createElement('style');s.id='mfSafe20';s.textContent=`
#mfThemeBtn,.mfThemeGrid,.mfThemeCard{display:none!important}
header .ha{gap:7px!important;align-items:center!important;flex-wrap:nowrap!important}header .ha .ib,#mfStreak,#mfBell,#eye{width:45px!important;min-width:45px!important;height:45px!important;min-height:45px!important;border-radius:14px!important;padding:0!important;font-size:20px!important;display:grid!important;place-items:center!important;transform:none!important}#mfStreak span{font-size:10px!important;line-height:10px!important}
@keyframes mfSafeTab{0%{opacity:.35;transform:translateY(7px) scale(.992)}100%{opacity:1;transform:none}}@keyframes mfSafePop{0%{opacity:0;transform:translate(-50%,-50%) scale(.55)}20%{opacity:1;transform:translate(-50%,-50%) scale(1.18)}45%{transform:translate(-50%,-50%) scale(1)}78%{opacity:1;transform:translate(-50%,-58%) scale(1)}100%{opacity:0;transform:translate(-50%,-76%) scale(.93)}}@keyframes mfSafePulse{0%{transform:scale(1)}45%{transform:scale(1.045)}100%{transform:scale(1)}}@keyframes mfSafeRise{0%{opacity:0;transform:translateY(10px)}100%{opacity:1;transform:none}}@keyframes mfSafeGlow{0%,100%{box-shadow:0 0 0 rgba(67,215,200,0)}50%{box-shadow:0 0 25px rgba(67,215,200,.14)}}
.v.on{animation:mfSafeTab .24s cubic-bezier(.2,.8,.2,1)}button,.q,.cat,.mini,.c,.txn,.datebox,.rank{transition:transform .14s ease,filter .14s ease,box-shadow .2s ease,border-color .2s ease}button:active,.q:active,.cat:active{transform:scale(.965)!important;filter:brightness(1.1)}.c:active,.mini:active,.datebox:active{transform:scale(.992)}.mfSafeRise{animation:mfSafeRise .28s ease both}.mfSafePulse{animation:mfSafePulse .34s ease}.prog i{transition:width .65s cubic-bezier(.2,.8,.2,1)!important}.hero{animation:mfSafeGlow 2.6s ease 1}
.mfMoneyPop20{position:fixed;left:50%;top:45%;z-index:60000;pointer-events:none;white-space:nowrap;font-size:46px;font-weight:950;letter-spacing:-1.5px;animation:mfSafePop 1.05s cubic-bezier(.18,.84,.24,1) both;text-shadow:0 8px 34px currentColor;filter:drop-shadow(0 0 16px currentColor)}.mfMoneyPop20.income{color:#4ade80}.mfMoneyPop20.expense{color:#fb7185}.mfMoneyPop20 small{display:block;text-align:center;font-size:12px;letter-spacing:0;margin-top:5px;opacity:.88}
.navin{grid-template-columns:repeat(5,1fr)!important}.nav button[data-v="insights"]{display:none!important}
@media(max-width:390px){header .ha{gap:5px!important}header .ha .ib,#mfStreak,#mfBell,#eye{width:42px!important;min-width:42px!important;height:42px!important;min-height:42px!important;font-size:19px!important}.mfMoneyPop20{font-size:40px!important}}
`;document.head.appendChild(s)}
function cleanThemes(){try{localStorage.removeItem('mf_theme')}catch{}document.body.classList.remove('mfThemeMidnight','mfThemeEmerald','mfThemeBeitar');document.getElementById('mfThemeBtn')?.remove();document.querySelectorAll('.mfThemeGrid,.mfThemeCard').forEach(x=>x.remove())}
function removeInsights(){document.querySelector('.nav button[data-v="insights"]')?.remove();const n=document.querySelector('.navin');if(n)n.style.gridTemplateColumns='repeat(5,1fr)'}
function moneyPop(kind,amount){document.querySelector('.mfMoneyPop20')?.remove();const d=document.createElement('div');d.className='mfMoneyPop20 '+kind;d.innerHTML=`${kind==='expense'?'−':'+'}₪${Math.round(+amount||0).toLocaleString('he-IL')}<small>${kind==='expense'?'הוצאה נוספה':'הכנסה נוספה'}</small>`;document.body.appendChild(d);try{navigator.vibrate?.(kind==='expense'?[18]:[12,28,12])}catch{}setTimeout(()=>d.remove(),1100)}
function wrapSave(){if(window.__mfSafeSave20||typeof window.saveTx!=='function')return false;const old=window.saveTx;window.__mfSafeSave20=1;window.saveTx=async function(){const amount=+(document.getElementById('amount')?.value||0),k=window.kind||'income';const before=document.getElementById('amount')?.value;const r=await old.apply(this,arguments);const after=document.getElementById('amount')?.value;if(amount>0&&before&&after==='')setTimeout(()=>moneyPop(k,amount),40);return r};return true}
function wrapShow(){if(window.__mfSafeShow20||typeof window.show!=='function')return false;const old=window.show;window.__mfSafeShow20=1;window.show=function(v){const r=old.apply(this,arguments);requestAnimationFrame(()=>{const sec=document.getElementById(v);if(sec){sec.classList.remove('mfSafeRise');void sec.offsetWidth;sec.classList.add('mfSafeRise')}});return r};return true}
function micro(){document.addEventListener('click',e=>{const x=e.target.closest('.q,.cat,.btn,.datebox,.mini');if(!x)return;x.classList.remove('mfSafePulse');void x.offsetWidth;x.classList.add('mfSafePulse');setTimeout(()=>x.classList.remove('mfSafePulse'),420)},true)}
function init(){addStyle();cleanThemes();removeInsights();micro();let tries=0;const timer=setInterval(()=>{cleanThemes();removeInsights();const a=wrapSave(),b=wrapShow();if((a||window.__mfSafeSave20)&&(b||window.__mfSafeShow20)&&++tries>2)clearInterval(timer);if(++tries>80)clearInterval(timer)},100);new MutationObserver(()=>{cleanThemes();removeInsights()}).observe(document.body,{childList:true,subtree:true})}
ready(init)
})();