(()=>{
const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn();
let mfMe=null,mfDefaultsDone=false,mfHistoryRange='week';
function addStyle(){if(document.getElementById('mfSafe20'))return;const s=document.createElement('style');s.id='mfSafe20';s.textContent=`
#mfThemeBtn,.mfThemeGrid,.mfThemeCard{display:none!important}
header .ha{gap:7px!important;align-items:center!important;flex-wrap:nowrap!important}header .ha .ib,#mfStreak,#mfBell,#eye{width:45px!important;min-width:45px!important;height:45px!important;min-height:45px!important;border-radius:14px!important;padding:0!important;font-size:20px!important;display:grid!important;place-items:center!important;transform:none!important}#mfStreak span{font-size:10px!important;line-height:10px!important}
@keyframes mfSafeTab{0%{opacity:.35;transform:translateY(7px) scale(.992)}100%{opacity:1;transform:none}}@keyframes mfSafePop{0%{opacity:0;transform:translate(-50%,-50%) scale(.55)}20%{opacity:1;transform:translate(-50%,-50%) scale(1.18)}45%{transform:translate(-50%,-50%) scale(1)}78%{opacity:1;transform:translate(-50%,-58%) scale(1)}100%{opacity:0;transform:translate(-50%,-76%) scale(.93)}}@keyframes mfSafePulse{0%{transform:scale(1)}45%{transform:scale(1.045)}100%{transform:scale(1)}}@keyframes mfSafeRise{0%{opacity:0;transform:translateY(10px)}100%{opacity:1;transform:none}}
.v.on{animation:mfSafeTab .24s cubic-bezier(.2,.8,.2,1)}button,.q,.cat,.mini,.c,.txn,.datebox,.rank{transition:transform .14s ease,filter .14s ease,box-shadow .2s ease,border-color .2s ease}button:active,.q:active,.cat:active{transform:scale(.965)!important;filter:brightness(1.1)}.c:active,.mini:active,.datebox:active{transform:scale(.992)}.mfSafeRise{animation:mfSafeRise .28s ease both}.mfSafePulse{animation:mfSafePulse .34s ease}.prog i{transition:width .65s cubic-bezier(.2,.8,.2,1)!important}
.mfMoneyPop20{position:fixed;left:50%;top:45%;z-index:60000;pointer-events:none;white-space:nowrap;font-size:46px;font-weight:950;letter-spacing:-1.5px;animation:mfSafePop 1.05s cubic-bezier(.18,.84,.24,1) both;text-shadow:0 8px 34px currentColor}.mfMoneyPop20.income{color:#4ade80}.mfMoneyPop20.expense{color:#fb7185}.mfMoneyPop20 small{display:block;text-align:center;font-size:12px;letter-spacing:0;margin-top:5px;opacity:.88}
.navin{grid-template-columns:repeat(5,1fr)!important}.nav button[data-v="insights"]{display:none!important}
.mfHistoryRanges{display:flex;gap:6px;overflow-x:auto;scrollbar-width:none;padding:3px 0 8px;margin-top:8px}.mfHistoryRanges::-webkit-scrollbar{display:none}.mfHistoryRanges button{flex:0 0 auto;min-height:36px;border:1px solid #2e435c;border-radius:999px;background:#0b1725;color:#9fb0c4;padding:0 12px;font-size:12px;font-weight:850}.mfHistoryRanges button.on{background:#17364a;color:#fff;border-color:#43d7c8;box-shadow:0 0 0 1px #43d7c822 inset}
@media(max-width:390px){header .ha{gap:5px!important}header .ha .ib,#mfStreak,#mfBell,#eye{width:42px!important;min-width:42px!important;height:42px!important;min-height:42px!important;font-size:19px!important}.mfMoneyPop20{font-size:40px!important}.mfHistoryRanges{margin-left:-2px;margin-right:-2px}.mfHistoryRanges button{padding:0 10px}}
`;document.head.appendChild(s)}
function cleanThemes(){try{localStorage.removeItem('mf_theme')}catch{}document.body.classList.remove('mfThemeMidnight','mfThemeEmerald','mfThemeBeitar');document.getElementById('mfThemeBtn')?.remove();document.querySelectorAll('.mfThemeGrid,.mfThemeCard').forEach(x=>x.remove())}
function removeInsights(){document.querySelector('.nav button[data-v="insights"]')?.remove();const n=document.querySelector('.navin');if(n)n.style.gridTemplateColumns='repeat(5,1fr)'}
function moneyPop(kind,amount){document.querySelector('.mfMoneyPop20')?.remove();const d=document.createElement('div');d.className='mfMoneyPop20 '+kind;d.innerHTML=`${kind==='expense'?'−':'+'}₪${Math.round(+amount||0).toLocaleString('he-IL')}<small>${kind==='expense'?'הוצאה נוספה':'הכנסה נוספה'}</small>`;document.body.appendChild(d);setTimeout(()=>d.remove(),1100)}
async function detectMember(){if(mfMe)return mfMe;try{if(typeof sb==='undefined'||typeof sess==='undefined'||typeof hid==='undefined'||!sess||!hid)return null;const r=await sb.from('mf_members').select('display_name').eq('household_id',hid).eq('user_id',sess.user.id).maybeSingle();mfMe=r.data?.display_name||null;return mfMe}catch{return null}}
function personalizeGoals(){if(!mfMe)return;const sec=document.getElementById('goals');if(!sec)return;const cards=[...sec.children].filter(x=>x.classList?.contains('c'));const mine=cards.find(c=>(c.querySelector('h2')?.textContent||'').trim()===mfMe);if(!mine)return;const joint=cards.find(c=>(c.querySelector('h2')?.textContent||'').includes('היעדים שלנו'))||cards[0];if(joint&&joint.nextSibling!==mine)joint.after(mine);if(mfMe==='נועה'){const release=document.getElementById('releaseGoalCard');if(release&&mine.nextSibling!==release)mine.after(release)}}
function applyPersonalDefaults(){if(!mfMe||mfDefaultsDone)return;mfDefaultsDone=true;const fo=document.getElementById('fo');if(fo){fo.value=mfMe;if(typeof historyR==='function')historyR()}if(typeof ownerSet==='function')ownerSet(mfMe);personalizeGoals()}
function keepPersonalized(){if(mfMe)personalizeGoals()}
function rangeStart(){const now=new Date();now.setHours(0,0,0,0);if(mfHistoryRange==='all')return null;const d=new Date(now);if(mfHistoryRange==='today')return d;if(mfHistoryRange==='3d'){d.setDate(d.getDate()-2);return d}if(mfHistoryRange==='week'){d.setDate(d.getDate()-6);return d}if(mfHistoryRange==='month'){d.setDate(d.getDate()-29);return d}return null}
function addHistoryRanges(){const sec=document.getElementById('history');if(!sec||document.getElementById('mfHistoryRanges'))return;const search=document.getElementById('search');if(!search)return;const bar=document.createElement('div');bar.id='mfHistoryRanges';bar.className='mfHistoryRanges';bar.innerHTML=[['today','היום'],['3d','3 ימים'],['week','שבוע'],['month','חודש'],['all','הכול']].map(([v,l])=>`<button data-range="${v}" class="${v===mfHistoryRange?'on':''}">${l}</button>`).join('');search.after(bar);bar.querySelectorAll('button').forEach(b=>b.onclick=()=>{mfHistoryRange=b.dataset.range;bar.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));if(typeof historyR==='function')historyR()})}
function wrapHistory(){if(window.__mfHistoryRangeWrapped||typeof historyR!=='function')return false;window.__mfHistoryRangeWrapped=1;window.historyR=function(){try{const q=(document.getElementById('search')?.value||'').trim(),o=document.getElementById('fo')?.value||'',k=document.getElementById('fk')?.value||'',m=document.getElementById('fm')?.value||'',start=rangeStart(),end=new Date();end.setHours(23,59,59,999);let a=rs().filter(x=>{const z=new Date(x.transaction_date+'T00:00:00');return(!q||[x.person,x.category,x.note].join(' ').includes(q))&&(!o||x.person===o)&&(!k||x.kind===k)&&(!m||x.transaction_date.startsWith(m))&&(!start||(z>=start&&z<=end))});const hist=document.getElementById('hist');if(!hist)return;hist.innerHTML=a.length?a.map(x=>`<div class=txn><div><b>${esc(x.category)}</b><div class="mut sm">${x.person} · ${new Date(x.transaction_date+'T00:00:00').toLocaleDateString('he-IL')}${x.virtual?' · קבוע':''}</div></div><div><b class="${x.kind==='income'?'plus':'minus'}">${x.kind==='income'?'+':'-'}${F(x.amount)}</b>${x.virtual?'':`<br><button class="btn d" style="min-height:32px" onclick="del('${x.id}')">מחיקה</button>`}</div></div>`).join(''):'<p class=mut>אין תנועות בטווח הזה.</p>'}catch(e){}}
return true}
function wrapSave(){if(window.__mfSafeSave20||typeof saveTx!=='function')return false;const old=saveTx;window.__mfSafeSave20=1;window.saveTx=async function(){const amount=+(document.getElementById('amount')?.value||0),k=document.getElementById('kout')?.classList.contains('on')?'expense':'income',before=document.getElementById('amount')?.value;const r=await old.apply(this,arguments),after=document.getElementById('amount')?.value;if(amount>0&&before&&after==='')setTimeout(()=>moneyPop(k,amount),40);return r};return true}
function wrapShow(){if(window.__mfSafeShow20||typeof show!=='function')return false;const old=show;window.__mfSafeShow20=1;window.show=function(v){const r=old.apply(this,arguments);requestAnimationFrame(()=>{const sec=document.getElementById(v);if(sec){sec.classList.remove('mfSafeRise');void sec.offsetWidth;sec.classList.add('mfSafeRise')}if(v==='goals')keepPersonalized();if(v==='history'){addHistoryRanges();if(typeof historyR==='function')historyR()}});return r};return true}
function micro(){document.addEventListener('click',e=>{const x=e.target.closest('.q,.cat,.btn,.datebox,.mini');if(!x)return;x.classList.remove('mfSafePulse');void x.offsetWidth;x.classList.add('mfSafePulse');setTimeout(()=>x.classList.remove('mfSafePulse'),420)},true)}
function init(){addStyle();cleanThemes();removeInsights();micro();let tries=0;const timer=setInterval(async()=>{cleanThemes();removeInsights();addHistoryRanges();wrapHistory();wrapSave();wrapShow();if(!mfMe)await detectMember();if(mfMe)applyPersonalDefaults();if(++tries>100)clearInterval(timer)},120);new MutationObserver(()=>{cleanThemes();removeInsights();keepPersonalized();addHistoryRanges()}).observe(document.body,{childList:true,subtree:true})}
ready(init)
})();