const C='moneyflow-v9-clean-grants-v5';
self.addEventListener('install',e=>{self.skipWaiting()});
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())await caches.delete(k);await self.clients.claim();for(const c of await self.clients.matchAll({type:'window',includeUncontrolled:true})){try{c.navigate(c.url)}catch{}}})()));
function inject(h){const s=`<script>(function(){
const money=n=>'₪'+Math.round(+n||0).toLocaleString('he-IL');
function css(){if(document.getElementById('mfFixStyle'))return;const x=document.createElement('style');x.id='mfFixStyle';x.textContent='@keyframes mfFade{from{opacity:0}to{opacity:1}}@keyframes mfUp{from{opacity:0;transform:translateY(22px) scale(.985)}to{opacity:1;transform:none}}@keyframes mfOut{to{opacity:0;transform:translateY(18px) scale(.985)}}.mfOverlay{position:fixed;inset:0;z-index:10000;background:#050b14ed;backdrop-filter:blur(16px);padding:calc(14px + env(safe-area-inset-top)) 14px calc(30px + env(safe-area-inset-bottom));overflow:auto;color:#f6f8fb;animation:mfFade .18s ease}.mfSheet{max-width:540px;margin:auto;animation:mfUp .28s cubic-bezier(.2,.8,.2,1)}.mfOverlay.mfClosing{animation:mfFade .16s ease reverse both}.mfOverlay.mfClosing .mfSheet{animation:mfOut .16s ease both}.mfPersonRow{display:flex;justify-content:space-between;align-items:center;gap:10px;background:#101f31;border:1px solid #29425e;border-radius:16px;padding:12px;margin-top:8px;cursor:pointer}.mfPersonRow:active{transform:scale(.985)}.mfGrant{background:linear-gradient(145deg,#123441,#0b1c2d);border:1px solid #2a5369;border-radius:18px;padding:14px;margin:9px 0}.mfGoalCard{cursor:pointer;transition:.18s}.mfGoalCard:active{transform:scale(.985)}.mfEditBtn{min-height:34px!important;padding:0 11px!important;border-radius:11px!important;font-size:12px;white-space:nowrap}.mfEditHead{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px}';document.head.appendChild(x)}
function closeOverlay(box,after){box.classList.add('mfClosing');setTimeout(()=>{box.remove();if(after)after()},160)}
function removeOldGrants(){document.querySelectorAll('#goals .c').forEach(c=>{const text=(c.textContent||'').replace(/\s+/g,' ').trim();if(text.includes('מענקים צפויים')&&!c.id?.startsWith('mf'))c.remove()})}
function personNet(a,p){return(a||[]).filter(x=>x.person===p).reduce((s,x)=>s+(x.kind==='income'?+x.amount:-x.amount),0)}
function goalHistory(p){css();let rows=[],goal=0,title='';if(p==='איתי'){goal=+(set.itay_weekly_goal||1779.41);for(let k=0;k<8;k++){const w=ws(-k),v=personNet(w.a,'איתי'),en=new Date(w.d);en.setDate(en.getDate()+6);rows.push({l:w.d.toLocaleDateString('he-IL',{day:'2-digit',month:'2-digit'})+'–'+en.toLocaleDateString('he-IL',{day:'2-digit',month:'2-digit'}),v,ok:v>=goal})}title='איתי · שבועות אחרונים'}else{goal=+(set.noa_monthly_goal||7000);for(let k=0;k<6;k++){const m=ms(-k),v=personNet(m.a,'נועה'),d=new Date(),md=new Date(d.getFullYear(),d.getMonth()-k,1);rows.push({l:md.toLocaleDateString('he-IL',{month:'long',year:'numeric'}),v,ok:v>=goal})}title='נועה · חודשים אחרונים'}const box=document.createElement('div');box.className='mfOverlay';box.innerHTML='<div class="mfSheet"><div class="row"><div><h2 style="margin:0">'+title+'</h2><div class="mut sm">'+rows.filter(x=>x.ok).length+' מתוך '+rows.length+' עמדו ביעד</div></div><button class="btn s" id="mfClose">סגור</button></div><div class="c hero"><div class="row"><span>יעד לתקופה</span><b>'+money(goal)+'</b></div></div>'+rows.map(r=>'<div class="txn"><div><b>'+r.l+'</b><div class="sm '+(r.ok?'good':'bad')+'">'+(r.ok?'✓ היעד הושג':'✕ היעד לא הושג')+'</div></div><div style="text-align:left"><b>'+money(r.v)+'</b><div class="mut sm">מתוך '+money(goal)+'</div></div></div>').join('')+'</div>';document.body.appendChild(box);box.querySelector('#mfClose').onclick=()=>closeOverlay(box);box.onclick=e=>{if(e.target===box)closeOverlay(box)}}
function grantDetails(p){css();const it=p==='איתי',c=calc(),cur=it?c.i:c.n,goal=it?+(set.itay_release_goal||150000):+(set.noa_goal||130000),date=it?(set.itay_release_date||'2027-04-04'):(set.two_year_goal_date||'2028-08-17'),grants=it?[['מענק שחרור',+set.itay_release_grant||15000],['תוספת צפויה',+set.itay_expected_extra||2500]]:[['מענק',+set.noa_grant||10000],['חיסכון לכל ילד',+set.noa_child_savings||15000],['תוספת צפויה',+set.noa_expected_extra||2500]],total=grants.reduce((s,x)=>s+x[1],0),d=new Date(date+'T00:00:00');const box=document.createElement('div');box.className='mfOverlay';box.innerHTML='<div class="mfSheet"><div class="row"><div><div class="mut sm">תאריך יעד</div><h2 style="margin:2px 0">'+p+' · '+d.toLocaleDateString('he-IL')+'</h2></div><button class="btn s" id="mfClose">סגור</button></div><div class="c hero"><div class="row"><div><div class="mut sm">הון נוכחי</div><b style="font-size:24px">'+money(cur)+'</b></div><div style="text-align:left"><div class="mut sm">יעד</div><b style="font-size:24px">'+money(goal)+'</b></div></div><div class="mut sm" style="margin-top:8px">כולל מענקים צפויים: '+money(cur+total)+'</div></div><h2>מענקים צפויים</h2>'+grants.map(g=>'<div class="mfGrant"><div class="row"><span>'+g[0]+'</span><b class="good">+'+money(g[1])+'</b></div></div>').join('')+'<div class="txn"><b>סה״כ מענקים</b><b class="good">'+money(total)+'</b></div></div>';document.body.appendChild(box);box.querySelector('#mfClose').onclick=()=>closeOverlay(box);box.onclick=e=>{if(e.target===box)closeOverlay(box)}}
function editGoals(){css();const card=[...document.querySelectorAll('#goals .c')].find(c=>(c.querySelector('h2')?.textContent||'').trim()==='עריכת יעדים');if(!card)return;const home=card.parentNode,next=card.nextSibling;card.style.display='block';const box=document.createElement('div');box.className='mfOverlay';const sheet=document.createElement('div');sheet.className='mfSheet';sheet.innerHTML='<div class="mfEditHead"><div><div class="mut sm">הגדרות</div><h2 style="margin:2px 0">עריכת יעדים</h2></div><button class="btn s" id="mfEditClose">סגור</button></div>';sheet.appendChild(card);box.appendChild(sheet);document.body.appendChild(box);const restore=()=>{if(next&&next.parentNode===home)home.insertBefore(card,next);else home.appendChild(card);card.style.display='none'};box.querySelector('#mfEditClose').onclick=()=>closeOverlay(box,restore);box.onclick=e=>{if(e.target===box)closeOverlay(box,restore)}}
function hookEdit(cards){const edit=cards.find(c=>c.querySelector('h2')?.textContent.trim()==='עריכת יעדים');if(edit)edit.style.display='none';const hero=cards.find(c=>c.classList.contains('hero')&&(c.textContent||'').includes('היעדים שלנו'));if(hero&&!hero.querySelector('#mfEditGoalsBtn')){const h=hero.querySelector('h2');if(h){const wrap=document.createElement('div');wrap.className='row';h.parentNode.insertBefore(wrap,h);wrap.appendChild(h);const b=document.createElement('button');b.id='mfEditGoalsBtn';b.className='btn s mfEditBtn';b.textContent='✎ עריכה';b.onclick=e=>{e.stopPropagation();editGoals()};wrap.appendChild(b)}}}
function hook(){css();removeOldGrants();const cards=[...document.querySelectorAll('#goals .c')];hookEdit(cards);for(const p of ['איתי','נועה']){const card=cards.find(c=>c.querySelector('h2')?.textContent.trim()===p);if(card&&!card.dataset.mfHist){card.dataset.mfHist='1';card.classList.add('mfGoalCard');const hint=document.createElement('div');hint.className='mut sm';hint.style.cssText='margin-top:10px;display:flex;justify-content:space-between';hint.innerHTML='<span>'+(p==='איתי'?'8 השבועות האחרונים':'6 החודשים האחרונים')+'</span><b style="color:#72eadb">פירוט ›</b>';card.appendChild(hint);card.onclick=e=>{if(!e.target.closest('button,input,select'))goalHistory(p)}}}const dates=cards.find(c=>c.querySelector('h2')?.textContent.trim()==='תאריכי יעד');if(dates&&!dates.dataset.mfDates){dates.dataset.mfDates='1';const lab=document.createElement('div');lab.className='mut sm';lab.style.marginTop='14px';lab.textContent='פירוט אישי ומענקים';dates.appendChild(lab);for(const p of ['איתי','נועה']){const r=document.createElement('div');r.className='mfPersonRow';r.innerHTML='<div><b>'+p+'</b><div class="mut sm">תאריך יעד ומענקים</div></div><b style="color:#72eadb">פירוט ›</b>';r.onclick=()=>grantDetails(p);dates.appendChild(r)}}removeOldGrants()}
function addBell(){const h=document.querySelector('header .ha');if(!h||document.getElementById('mfBell'))return;const b=document.createElement('button');b.id='mfBell';b.className='ib';b.textContent='🔔';b.onclick=async()=>{if('Notification'in window){const r=await Notification.requestPermission();alert(r==='granted'?'ההתראות הופעלו':'ההתראות לא אושרו')}};h.prepend(b)}
function init(){hook();addBell();new MutationObserver(()=>{hook();removeOldGrants()}).observe(document.body,{childList:true,subtree:true})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();<\/script>`;return h.replace('</body>',s+'</body>')}
self.addEventListener('fetch',e=>{const r=e.request,u=new URL(r.url);if(r.method!=='GET'){e.respondWith(fetch(r));return}if(r.mode==='navigate'||u.pathname==='/'||u.pathname.endsWith('/index.html')){e.respondWith((async()=>{const x=await fetch(r,{cache:'no-store'});return new Response(inject(await x.text()),{status:x.status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})})());return}e.respondWith(fetch(r))});